### ISSUE TITLE
Library not found for -lAppboyKitLibrary

### ISSUE THREAD

**Issue by kikettas** [braze-inc/braze-ios-sdk#1]
After updating to the latest version (3.34.0), and also after cleaning the project and derived data, if I do another build (the first time you build it works) it throws the following error, preventing the project to build.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/9082270/110318868-580bd500-800e-11eb-8d35-a93fb5008065.png">

Any clue on what's going on here?

**Comment by bdrelling** [comment]
We're still seeing this as well in versions 4.0.0 and the newly released 4.0.1.

![image](https://user-images.githubusercontent.com/3022693/111710983-cc1d5880-8818-11eb-9650-7985bb579161.png)

cc @chshapiro

**Comment by hokstuff** [comment]
Hi @kikettas and @adrgrondin,

Sorry about the delay on this thread! The original issue seems to be same as the one described here: https://github.com/Appboy/appboy-ios-sdk/issues/283

You can update to [version 4.0.1](https://github.com/braze-inc/braze-ios-sdk/releases/tag/4.0.1) and that should allow you to build successive times without getting that error.

----

@bdrelling,

It appears that the error you are getting is a different one than the original post. Can you describe how you are getting your error? Is this also only when you build successive times in Xcode while using SPM? I see you have mentioned some of the problems you're experiencing in the Github issue you linked above, but please provide more info so we can try to repro on our end. Feel free to open a new issue if it is separate from this one.

**Comment by bdrelling** [comment]
> It appears that the error you are getting is a different one than the original post. Can you describe how you are getting your error? Is this also only when you build successive times in Xcode while using SPM? I see you have mentioned some of the problems you're experiencing in the Github issue you linked above, but please provide more info so we can try to repro on our end. Feel free to open a new issue if it is separate from this one.

@hokstuff half of our team was unable to do a first build, half of our team was able to clean and rebuild and have it work every time (but if they didn't clean, it would fail).

I'm happy to open up a new issue if we continue to see this in 4.0.1+ as you mentioned, I just assumed this was related and didn't want to cause issue bloat.

Thanks!

**Comment by hokstuff** [comment]
Hi @bdrelling,

Ah that's interesting - we haven't experienced this on our side after using 4.0.1, so it sounds like your issues may be a bit different.

Would you be able to share more info about your team's setup? In this situation, I think creating a new issue with your integration details (Segment, SPM, etc) would help give us more context. If you feel more comfortable, you can also contact us through support@braze.com if you don't want to share the info publicly.

Thanks!

**Comment by bdrelling** [comment]
@hokstuff sorry for the delay! I meant to respond and clarify that we haven't seen the issue yet on 4.0.1+, but if we do, I'll be sure to open an issue and send more details along!

Thank you!

**Comment by hokstuff** [comment]
@bdrelling Thanks for clarifying! And that sounds good to me - I'll close out this particular issue since the problem in the original post should be handled now.
