### ISSUE TITLE
In-app message (Full Screen, Modal) not displayed using Braze SDK 4.4.2 with SPM

### ISSUE THREAD

**Issue by hervouinc** [braze-inc/braze-ios-sdk#11]
Since we migrated our dependency manager from Carthage to Swift Package Manager, the Braze modal & full screens are not displayed anymore.

We use the version 4.4.2 of the SDK.
We tried with both SDKs v4.4.2. from https://github.com/braze-inc/braze-ios-sdk & https://github.com/Appboy/appboy-ios-sdk

Push notifications are well delivered.

While testing a draft campaign of "in-app message" (modal, full screen or slide-up) using a test user uuid or email, the push with title "Tap to see Test in-app message" is well received. But clicking on it doesn't make the message appear on the screen.

Note: The issue also happen after launching the campaign.

**Comment by lowip** [comment]
Closing in favor of https://github.com/Appboy/appboy-ios-sdk/issues/338.
