### ISSUE TITLE
setLastKnownLocationWithLatitude does not work

### ISSUE THREAD

**Issue by vaidotasbucinskas** [braze-inc/braze-ios-sdk#13]
Using `setLastKnownLocationWithLatitude(latitude: latitude, longitude: longitude, horizontalAccuracy: horizontalAccuracy, altitude: altitude, verticalAccuracy: verticalAccuracy)` to manually set the last known location for the user does not work.
The following error is returned: 
`The given parameters: latitude xx.xxxxxx([-90, 90]), longitude 0.000000([-180, 180]), horizontalAccuracy 13196.881470([0,∞)), altitude 0.000000, verticalAccuracy 0.000000([0,∞)), are not in the valid range, ignoring this location.`
It seems the latitude and longitude are mixed and longitude is always converted to zero.
Using `setLastKnownLocationWithLatitude(latitude: latitude, longitude: longitude, horizontalAccuracy: horizontalAccuracy)` works fine though.

SDK version `4.4.3`

**Comment by Bucimis** [comment]
@vaidotasbucinskas thanks for getting in touch. Why is your latitude printing out as `xx.xxxxxx` in the error message?

**Comment by vaidotasbucinskas** [comment]
I do not want to expose my coordinates 🙂. It's in the given range though.

**Comment by Bucimis** [comment]
@vaidotasbucinskas could you show the logs and the call site with values that repro the issue (can be different from your real location - if only your location causes the issue, we can strategize further)? Without knowing the inputs + logging output exactly it'll be difficult for us to debug.

Also it might be worth checking the type of your inputs - they should be of type `double`.

**Comment by vaidotasbucinskas** [comment]
@Bucimis I now see what's the issue. I usually get -1 verticalAccuracy with my device and my location immediatly gets rejected. Not sure why it always returns -1, maybe because my precise location is turned off. Even though Apple documentation says, that 0 or negative verticalAccuracy is invalid, but imho the location itself should not be rejected because of that.

**Comment by Bucimis** [comment]
@vaidotasbucinskas thanks for following up and good find. We'll look into being more permissive on inputs but for now I would recommend not passing in altitude or vertical accuracy (use the method with this signature https://github.com/braze-inc/braze-ios-sdk/blob/952a1832e6d1209b436837303b9d46b78dc6b5af/AppboyKit/include/ABKUser.h#L284) if you don't receive a valid vertical accuracy
