### ISSUE TITLE
NSInvalidArgumentException when calling start(withApiKey:inApplication:withLaunchOptions:)

### ISSUE THREAD

**Issue by victorBaro** [braze-inc/braze-ios-sdk#3]
We have recently launched a new version of our app and have seen a dramatic decline in user actions in Braze. 
After some debugging, we noticed this message in the console:

```
2021-06-10 20:02:01.888471-0700  [APPBOY] Exception NSInvalidArgumentException caught in Braze method initWithApiKey:withAppboyOptions:: +[ABKPersistentData configureForDataVersioning]: unrecognized selector sent to class 0x11451d470
```

This exception is raised right after calling:
```swift
//AppDelegate
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
  //...
  Appboy.start(withApiKey: "XXXX-XXXX-XXX-XXX-XXXX"), in: application, withLaunchOptions: launchOptions)
```

Before that last release we imported Appboy SDK using Cocoapods. For this new release of our app we switched to SPM.
Notice that we used to import from Appboy repo with
```
pod 'Appboy-iOS-SDK/Core'
```

**Comment by victorBaro** [comment]
Guessing this is related: https://github.com/Appboy/appboy-ios-sdk/issues/263

For reference, we have our main app Universe, which has an internal SPM module (UniverseAnalytics), which has Braze as dependency.
The main target has `-ObjC` as linked flag, but not UniverseAnalytics (given that SPM does not support this yet)

**Comment by hokstuff** [comment]
Hi @victorBaro,

I suspect that the `unrecognized selector` error is showing up within your `UniverseAnalytics` module, since that is the code that is calling the Braze SDK. Because it is not linking to the Braze SDK using `-ObjC`, I believe that is why it can't find the actual implementation code.

Are you able to edit your internal `UniverseAnalytics` module to use the `-ObjC` flag inside the original project?

**Comment by hokstuff** [comment]
Closing out this issue due to inactivity. If this was done in error or if you have any follow-ups, feel free to reach out to support@braze.com. Thanks!
