### ISSUE TITLE
`CGFloat` warnings in `ABKInAppMessage.h`

### ISSUE THREAD

**Issue by mathaeus** [braze-inc/braze-ios-sdk#4]
Several warnings in `ABKInAppMessage.h` when SDK is integrated via SPM

Affected versions: `4.3.0` and below

```
Implicit conversion increases floating-point precision: 'float' to 'CGFloat' (aka 'double')
```

<img width="1322" alt="warnings" src="https://user-images.githubusercontent.com/5389635/124239765-5369b000-db1a-11eb-8490-26dbf2885c6b.png">

**Comment by lowip** [comment]
Hi @mathaeus,

Thanks for reporting this issue, we are tracking it internally and will report here once the fix is released.
