### ISSUE TITLE
Compiler error when integrating library with SPM and Xcode 13 beta 3

### ISSUE THREAD

**Issue by martinknabbe** [braze-inc/braze-ios-sdk#5]
# Report

## What did you do?

Integrating AppboyKit and AppboyUI with Swift Package Manager and Xcode 13 beta 3 (13A5192i).

## What did you expect to happen?

Library compiles without errors.

## What happened instead?

Compiler emits error 
- `'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`
- `'openURL:' is unavailable: not available on iOS (App Extension)`

This error appears due to the changes in the linker mentioned in the [Xcode release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes)

> Resolved in Xcode 13 Beta 3
> 
> Linking Swift packages from application extension targets or watchOS applications no longer emits unresolvable warnings about linking to libraries not safe for use in application extensions. This means that code referencing APIs annotated as unavailable for use in app extensions must now themselves be annotated as unavailable for use in application extensions, in order to allow that code to be used in both apps and app extensions. (66928265)

All libraries that use API marked as unavailable in iOS app extensions, such as `UIApplication.shared`, have to mark their code themself with `@available(iOSApplicationExtension, unavailable)` in Swift and `NS_EXTENSION_UNAVAILABLE` in Objective-C.

## Environment

Xcode Version: 13 beta 3 (13A5192i)
Appboy SDK Version: 4.0.2
Deployment Target: iOS 11.4
Base SDK: 15.0
Method of Integration: Swift Package Manager

**Comment by lowip** [comment]
Hi @martinknabbe,

Thank you for reporting the issue, we're tracking it internally and will update here once we have released a fix.

Best,

**Comment by JoeMcCrawCBS** [comment]
I'm also experiencing this issue(it is also occurring in beta 4).

**Comment by JoeMcCrawCBS** [comment]
Updating to beta 5 fixed this issue for me.

**Comment by hokstuff** [comment]
We have verified that Xcode 13 beta 5 fixes the compiler errors described in the original post. Thanks for reporting the issue and investigating!
