### ISSUE TITLE
Swift package not compiling

### ISSUE THREAD

**Issue by ronenmetaiev** [braze-inc/braze-ios-sdk#6]
Hello
I recently move your SDK from pods to SPM, and I cant compile , get the following error
"artifact of binary target 'AppboyKitLibrary' failed download. the request timed out"
attached image

please advice
Thanks

<img width="386" alt="Screen Shot 2021-08-18 at 12 26 44" src="https://user-images.githubusercontent.com/34416580/129873962-e8361dbb-aec7-4dd0-a60c-c6c0fb011aa9.png">

**Comment by hokstuff** [comment]
Hi @ronenmetaiev,

Are you still experiencing this issue? Are you using a stable internet connection, and are you following [the integration steps here](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager/)? Feel free to reach out to support@braze.com if you have specific issues you'd like to discuss there.

**Comment by StasKeiss** [comment]
Hey @hokstuff,

We are having the same issue. It happens if we are connected to our wifi. All other libraries we use (+20) work just fine but this one fails for timeout. If we switch our connection to ethernet, it works. Maybe it has something to do with the size of the package? This kind of behavior happens only to this library.

**Comment by hokstuff** [comment]
Hi @StasKeiss,

I have a few questions to help debug this:
- Are you using the latest version of Swift?
- How often are you able to repro this error?
- Which versions of our SDK do you experience this issue?

Thanks!

**Comment by hokstuff** [comment]
I'm closing out this issue due to inactivity. If you have further follow ups around this, please reach out to support@braze.com. Thanks!
