### ISSUE TITLE
[ABKPersistentData configureForDataVersioning]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by MadsBogeskov** [braze-inc/braze-ios-sdk#7]
We are currently getting a single error each time we launch our app that says:
```
2021-11-01 08:57:44.876166+0100 APP[24258:4300106] +[ABKPersistentData configureForDataVersioning]: unrecognized selector sent to class 0x1132ee248
```

We are using AppBoy v 4.4.0 via SPM.

**Comment by Bucimis** [comment]
@MadsBogeskov thanks for getting in touch. 

1. Is this happening on every app start
2. Does it crash the app?
3. Does this happen both when the app is already installed, and on a fresh install?

**Comment by Bucimis** [comment]
Also, did you add the `-ObjC` flag to your project? https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods/swift_package_manager/#step-1-adding-the-dependency-to-your-project

**Comment by hokstuff** [comment]
Hi @MadsBogeskov,

Are you still experiencing this issue?

**Comment by hokstuff** [comment]
I'm closing out this issue due to inactivity. Please feel free to comment or contact support@braze.com if the workaround provided above doesn't work. Thanks!

**Comment by cheif** [comment]
Just wanted to drop by and say that I also got this error, and this meant that the SDK wasn't initiated properly. Strangely though `Appboy.sharedInstance()` was non-nil, but I couldn't see any sessions in the dashboard.

Adding `-ObjC` to `Other Linker Flags` fixed it for me, just like @Bucimis, so this is probably the correct solution for anyone else having this error
