### ISSUE TITLE
braze-ios-sdk In-App-Message does not open deeplinks without path or asset attached

### ISSUE THREAD

**Issue by lucoceano** [braze-inc/braze-ios-sdk#9]
The title says most of it. But we were trying to open a deep link from and In-App-Message and it was not working, after debuting the SDK we manage to find that [this line](https://github.com/braze-inc/braze-ios-sdk/blob/master/AppboyUI/ABKInAppMessage/ViewControllers/ABKInAppMessageHTMLBaseViewController.m#L160), when both the path and assets are `nil` it will return `YES` making the app open the URL in the web view, even for deep link URLs.

We manage to work around it by adding an empty zip file to the assets field or adding a path to the deep link, but would be great to have it looked after in the SDK.

**Comment by lowip** [comment]
Hi @lucoceano,

Thanks for reporting this issue. We are tracking it internally and will update here once a fix is released.

Just to make sure I understood it right, you're experiencing the issue when using a deeplink that only contains the scheme part of the url (e.g. `my-app://`)?

**Comment by lucoceano** [comment]
yeah, they look like this `my-app://?foo=bar&bar=foo`

**Comment by davidbielik** [comment]
Hi @lucoceano thanks for raising this and for identifying a workaround. We've decided to address this in our upcoming Swift SDK (internal ticket: SDK-2157) and won't be fixed here.
